name: Hello, World!
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          curl -vv -H "Authorization: token ${secrets.REPO_GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/w-haibara/submod_action_main/dispatches" -d '{"event_type": "build", "client_payload": {"hoge": "fuga"}}'
